config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_scope :user do
    get '/users/sign_up', to: "user/registrations#new"
    post '/users', to: "user/registrations#create"
    get '/users/sign_in', to: "user/sessions#new"
    delete '/users/sign_out', to: "user/sessions#destroy"
    get 'users/forgot_password', to: "user/passwords#new"
  end
  resources :articles
end

app/views/shared/_flash_message.html.erb
<% if flash[:notice] || flash[:alert] %>
  <div class="alert <%= flash[:alert] ? 'alert-danger' : 'alert-success' %> alert-dismissible fade show mt-5" role="alert">
    <strong><%= flash[:notice] || flash[:alert] %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-warning">
  <div class="container-fluid">
    <%= link_to "Blog Application", root_path, method: "get",class:"navbar-brand active ms-5" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-5 ">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
          
        </li>
        <li class="nav-item">
          <%= link_to "Article", articles_path,class:"nav-link active"  %>
        </li> 
      <% if current_user %>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", users_sign_up_path, class:"nav-link active"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", users_sign_in_path, class:"nav-link active"  %>
        </li>
      <% end %>
      </ul>
      <ul class="navbar-nav d-flex me-5">
          <% if current_user %>
            <li class="nav-item dropdown">
              <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user&.email %>
              </a>
              <ul class="dropdown-menu">
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Log Out",users_sign_out_path, 'data-turbo-method': :delete, class: "dropdown-item " %>
              </ul>
            </li>    
          <% end %>  
        </ul>
    </div>
  </div>
</nav>